language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

#script: "./gradlew clean build"
script:
  - echo $AWS_ACCESS_KEY
  - echo $AWS_SECRET_KEY
  - "./gradlew clean bootJar"

before_deploy:
  - zip -r tdd-demo-webservice *
  - mkdir -p deploy
  - mv tdd-demo-webservice.zip deploy/tdd-demo-webservice.zip

deploy:
  provider: s3
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: tdd-demo-build
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - mjis4341@naver.com
